# enemy_color: "red"
enemy_color: "blue"

#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: GPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: 2.6 # degree -2.5
pitch_offset: 3.7 # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
decision_speed: 7 # rad/s
high_speed_delay_time: 0.015 # s
low_speed_delay_time: 0.013 # s planner use this value

#####-----shooter参数-----#####
first_tolerance: 8 # 近距离射击容差，degree
second_tolerance: 5 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

camera_name: "hikrobot"
exposure_ms: 3
gain: 16.9
vid_pid: "2bdf:0001"

#  1  0  0
#  0  1  0
#  0  0  1
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 重投影误差: 0.1077px
camera_matrix: [1783.1352455869924, 0, 712.25232126543733, 0, 1791.4823798103048, 573.49956992910597, 0, 0, 1]
distort_coeffs: [-0.078807913877987926, 0.15574954821119635, 0.00073002566867448159, 0.001210731408502146, 0]

# 相机同理想情况的偏角: yaw2.50 pitch-4.72 roll2.13 degree
R_camera2gimbal: [-0.046688242480313003, -0.080470535390043937, 0.99566294545299772, -0.99822331730532432, 0.040697652227314141, -0.043519075026227511, -0.037019141022629175, -0.99592579745542498, -0.082227666637953334]
t_camera2gimbal: [0.14816386746905794, 0.096371592867113956, 0.025967577445711799]

#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"
yaw_kp: 0
yaw_kd: 0
pitch_kp: 0
pitch_kd: 0

#####-----planner-----#####
fire_thresh: 0.003

max_yaw_acc: 50
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6, 0]
R_pitch: [1]

#####-----buff_detector参数-----#####
model: "assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.700   # s
predict_time: 0.115     # s
